### ISSUE TITLE
Can not create a backup (Windows)

### ISSUE THREAD

**Issue by MrOinky** [SushiInYourFace/YayaBot#23]
An error, like so is thrown on attempting to create a backup, potentially linked to being on Windows:
```
Traceback (most recent call last):
  File "C:\Users\<My User>\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 213, in on_command_error
    raise error
  File "C:\Users\<My User>\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\<My User>\Desktop\Dump 2, Electric Boogaloo\Github\YayaBot-main\cogs\owner.py", line 195, in create
    backup = sqlite3.connect(tempBackup.name)
sqlite3.OperationalError: unable to open database file
```
Presumably, this is related to accessing the temp file, as the error suggests.
Note: My username is replaced with <My User> (not that it really gives anything away)

**Comment by MrOinky** [comment]
Fixed!
